version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.build
        ports:
            - '3000:3000'
        tty: true
        command: ['./App-exe']
